version: '2'
services:
  db:
    image: mysql:5.7
    container_name: redux_docker_db
    env_file: .env
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
  wordpress:
    depends_on:
      - db
    build: wordpress
    container_name: redux_docker_wordpress
    env_file: .env
    entrypoint: []
    command: wp_setup.sh
    links:
      - db
    ports:
      - "5000:80"
    restart: always
  app:
    depends_on:
      - wordpress
    image: node:6.2
    container_name: redux_docker_app
    env_file: .env
    working_dir: /app
    command: npm run dev-start
    volumes:
      - ./app:/app
    links:
      - wordpress
    ports:
      - "8000:8000"
      - "8080:8080"