version: '2'
services:
  backend:
    image: node:6.2
    working_dir: /backend
    command: npm run dev
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    container_name: redux_docker_backend
    environment:
      NODE_ENV: ${NODE_ENV}